### ISSUE TITLE
Mod prints in-game messages to my twitch chat. 

### ISSUE THREAD

**Issue by Courageousodin** [faluhub/TwitchEmotes#2]
Don't know if this is an intended feature, but it's definitely not something I would want the mod to do. Every message sent in-game is sent to my offline chat on twitch. 
https://gyazo.com/a3d0c6703ab96b9da21d3a8246119120
https://gyazo.com/c105596daa36456810593b9b3c729760

Additionally, when I added the mod to my pack and exported it via modrinth to the people who play on my server, the export shipped my twitch credentials allowing them to write messages in-game, which would also be sent in my offline chat under my username. 
https://gyazo.com/5325619f41e9695bdfdcc609f23fc88a
https://gyazo.com/9bcbf6cce2872462408f1d00accb4869

For whatever reason it was only this user, KekuHD, who managed to retain my login credentials/token when they updated the pack we're using. Everyone else had to connect their own account, which leads me to a third bug. If you don't have an account linked, the mod causes the game to crash upon you sending a chat messge. Happened to me when testing the mod, and everyone who has installed the mod with the aforementioned exception of KekuHD.

**Comment by faluhub** [comment]
Hi. Yeah, this is intended. I originally had an option to disable this, but now that I'm looking at it, it got lost in the rewrite. I will fix this and the crash. For the credentials stuff, I don't really see what *I* could have done differently. When making the pack you shouldn't keep the config file for this mod as it stores sensitive Twitch creds. Thanks for bringing the former issues to light though, they'll be fixed shortly. :)

**Comment by faluhub** [comment]
Sorry, forgot to update you. New releases have been published for every version on modrinth. I did this yesterday but I forgot to update.
